name: Blazor App CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '**/labs/app_service_demo/**'

jobs:
  build-and-deploy:
    name: Build and Deploy Blazor to Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: labs/app_service_demo/blazor.trapistan

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Publish App
      run: dotnet publish -c Release -o ../../publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: trapistan
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: labs/app_service_demo/publish

    - name: Upload Publish Artifact
      uses: actions/upload-artifact@v3
      with:
        name: blazor.trapistan-webapp-deployment-publish
        path: labs/app_service_demo/publish