name: Deploy Blazor App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore Dependencies
      run: dotnet restore blazor.trapistan

    - name: Clean previous publish
      run: rm -rf ./publish

    - name: Publish .NET app
      run: dotnet publish blazor.trapistan -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: trapistan
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish

    # - name: Upload Publish Directory as Artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: blazor.trapistan-webapp-deployment-publish
    #     path: ./publish
